spring:
  application:
    name: fin-kids-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

app:
  bonus:
    execution:
      enabled: ${BONUS_EXECUTION_ENABLED:false}
      cron: ${BONUS_EXECUTION_CRON:0 5 0 1 * *}
      zone: ${BONUS_EXECUTION_ZONE:UTC}
      actor-email: ${BONUS_EXECUTION_ACTOR_EMAIL:system.bonus@granagalaxy.local}
